import type { AssessmentQuestion } from '@/types';

export const assessmentQuestions: AssessmentQuestion[] = [
  // ── Group 1: Intent ──
  {
    id: 'primary_goal',
    group: 'intent',
    groupLabel: 'WHAT BRINGS YOU HERE',
    groupDescription: 'Understanding your primary objective helps us focus your protocol.',
    question: "What's your primary goal?",
    type: 'card-select',
    required: true,
    options: [
      { label: 'I want to focus more consistently', value: 'focus' },
      { label: 'I want to sleep better', value: 'sleep' },
      { label: 'I want to recover faster', value: 'recovery' },
      { label: 'I want to feel more regulated', value: 'regulation' },
      { label: 'I want to perform better physically', value: 'physical' },
      { label: "I'm not sure — I want to understand my patterns", value: 'explore' },
    ],
  },
  {
    id: 'friction_point',
    group: 'intent',
    groupLabel: 'WHAT BRINGS YOU HERE',
    groupDescription: '',
    question: "What's your biggest friction point?",
    type: 'card-select',
    required: true,
    options: [
      { label: 'I crash in the afternoon', value: 'afternoon_crash' },
      { label: "I can't fall asleep easily", value: 'sleep_onset' },
      { label: "I wake up and don't feel rested", value: 'unrefreshed' },
      { label: 'I feel wired but tired', value: 'wired_tired' },
      { label: 'My energy is unpredictable', value: 'unpredictable' },
      { label: "I can't sustain focus for long periods", value: 'focus_duration' },
      { label: 'I struggle to wind down after intense work or training', value: 'wind_down' },
    ],
  },
  {
    id: 'tried_before',
    group: 'intent',
    groupLabel: 'WHAT BRINGS YOU HERE',
    groupDescription: '',
    question: 'What have you tried before?',
    type: 'multi-select',
    required: false,
    options: [
      { label: 'Caffeine management', value: 'caffeine' },
      { label: 'Melatonin', value: 'melatonin' },
      { label: 'Adaptogens', value: 'adaptogens' },
      { label: 'Nootropics', value: 'nootropics' },
      { label: 'Breathwork', value: 'breathwork' },
      { label: 'Cold exposure', value: 'cold' },
      { label: 'Meditation', value: 'meditation' },
      { label: 'Therapy', value: 'therapy' },
      { label: 'Prescription medication', value: 'prescription' },
      { label: 'Nothing specific', value: 'nothing' },
    ],
  },

  // ── Group 2: Baseline Patterns ──
  {
    id: 'wake_time',
    group: 'baseline',
    groupLabel: 'HOW YOUR DAYS TYPICALLY RUN',
    groupDescription: 'Your natural rhythm shapes when and how your protocol works best.',
    question: 'When do you typically wake up?',
    type: 'time-picker',
    required: true,
  },
  {
    id: 'sleep_time',
    group: 'baseline',
    groupLabel: 'HOW YOUR DAYS TYPICALLY RUN',
    groupDescription: '',
    question: 'When do you typically go to sleep?',
    type: 'time-picker',
    required: true,
  },
  {
    id: 'sleep_quality',
    group: 'baseline',
    groupLabel: 'HOW YOUR DAYS TYPICALLY RUN',
    groupDescription: '',
    question: 'How would you rate your typical sleep quality?',
    type: 'slider',
    sliderLabels: ['Poor', 'Excellent'],
    sliderMin: 1,
    sliderMax: 5,
    required: true,
  },
  {
    id: 'sleep_onset',
    group: 'baseline',
    groupLabel: 'HOW YOUR DAYS TYPICALLY RUN',
    groupDescription: '',
    question: 'How long does it typically take you to fall asleep?',
    type: 'card-select',
    required: true,
    options: [
      { label: 'Less than 10 minutes', value: 'under_10' },
      { label: '10–20 minutes', value: '10_20' },
      { label: '20–40 minutes', value: '20_40' },
      { label: '40+ minutes', value: 'over_40' },
    ],
  },
  {
    id: 'night_waking',
    group: 'baseline',
    groupLabel: 'HOW YOUR DAYS TYPICALLY RUN',
    groupDescription: '',
    question: 'How often do you wake during the night?',
    type: 'card-select',
    required: true,
    options: [
      { label: 'Rarely', value: 'rarely' },
      { label: '1–2 times', value: '1_2' },
      { label: '3+ times', value: '3_plus' },
      { label: 'Variable', value: 'variable' },
    ],
  },
  {
    id: 'morning_energy',
    group: 'baseline',
    groupLabel: 'HOW YOUR DAYS TYPICALLY RUN',
    groupDescription: '',
    question: 'How is your energy in the morning?',
    type: 'slider',
    sliderLabels: ['Need 30+ min to wake', 'Wake up sharp'],
    sliderMin: 1,
    sliderMax: 5,
    required: true,
  },
  {
    id: 'afternoon_energy',
    group: 'baseline',
    groupLabel: 'HOW YOUR DAYS TYPICALLY RUN',
    groupDescription: '',
    question: 'How is your energy in the afternoon?',
    type: 'slider',
    sliderLabels: ['Significant dip', 'Consistent'],
    sliderMin: 1,
    sliderMax: 5,
    required: true,
  },
  {
    id: 'caffeine',
    group: 'baseline',
    groupLabel: 'HOW YOUR DAYS TYPICALLY RUN',
    groupDescription: '',
    question: 'How much caffeine do you consume daily?',
    type: 'card-select',
    required: true,
    options: [
      { label: 'None', value: 'none' },
      { label: '1 cup', value: '1' },
      { label: '2–3 cups', value: '2_3' },
      { label: '4+ cups', value: '4_plus' },
      { label: 'Variable', value: 'variable' },
    ],
  },

  // ── Group 3: Training & Physical Load ──
  {
    id: 'training_frequency',
    group: 'training',
    groupLabel: 'HOW YOUR BODY MOVES',
    groupDescription: 'Physical load affects recovery needs and protocol timing.',
    question: 'How often do you train or exercise?',
    type: 'card-select',
    required: true,
    options: [
      { label: 'None', value: 'none' },
      { label: '1–2 times per week', value: '1_2' },
      { label: '3–4 times per week', value: '3_4' },
      { label: '5+ times per week', value: '5_plus' },
      { label: 'Variable', value: 'variable' },
    ],
  },
  {
    id: 'training_type',
    group: 'training',
    groupLabel: 'HOW YOUR BODY MOVES',
    groupDescription: '',
    question: 'What type of training do you do?',
    type: 'multi-select',
    required: false,
    options: [
      { label: 'Strength', value: 'strength' },
      { label: 'Endurance', value: 'endurance' },
      { label: 'HIIT', value: 'hiit' },
      { label: 'Yoga / Pilates', value: 'yoga_pilates' },
      { label: 'Sport-specific', value: 'sport' },
      { label: 'Walking only', value: 'walking' },
    ],
  },
  {
    id: 'training_time',
    group: 'training',
    groupLabel: 'HOW YOUR BODY MOVES',
    groupDescription: '',
    question: 'When do you typically train?',
    type: 'card-select',
    required: true,
    options: [
      { label: 'Morning', value: 'morning' },
      { label: 'Midday', value: 'midday' },
      { label: 'Afternoon', value: 'afternoon' },
      { label: 'Evening', value: 'evening' },
      { label: 'Variable', value: 'variable' },
    ],
  },
  {
    id: 'recovery_perception',
    group: 'training',
    groupLabel: 'HOW YOUR BODY MOVES',
    groupDescription: '',
    question: 'How well do you recover from training?',
    type: 'slider',
    sliderLabels: ['Often feel overtrained', 'Recover well'],
    sliderMin: 1,
    sliderMax: 5,
    required: true,
  },

  // ── Group 4: Stress & Nervous System ──
  {
    id: 'stress_level',
    group: 'stress',
    groupLabel: 'HOW YOUR SYSTEM RESPONDS TO LOAD',
    groupDescription: 'Your nervous system patterns shape how we build your protocol.',
    question: 'How would you rate your current stress level?',
    type: 'slider',
    sliderLabels: ['Low', 'High'],
    sliderMin: 1,
    sliderMax: 5,
    required: true,
  },
  {
    id: 'stress_pattern',
    group: 'stress',
    groupLabel: 'HOW YOUR SYSTEM RESPONDS TO LOAD',
    groupDescription: '',
    question: 'How would you describe your stress pattern?',
    type: 'card-select',
    required: true,
    options: [
      { label: 'Constant low hum', value: 'constant' },
      { label: 'Spikes and crashes', value: 'spikes' },
      { label: 'Mostly calm with occasional overwhelm', value: 'occasional' },
      { label: 'Persistently elevated', value: 'elevated' },
    ],
  },
  {
    id: 'anxiety_frequency',
    group: 'stress',
    groupLabel: 'HOW YOUR SYSTEM RESPONDS TO LOAD',
    groupDescription: '',
    question: 'How often do you experience anxiety?',
    type: 'card-select',
    required: true,
    options: [
      { label: 'Rarely', value: 'rarely' },
      { label: 'Sometimes', value: 'sometimes' },
      { label: 'Often', value: 'often' },
      { label: 'Daily', value: 'daily' },
    ],
  },
  {
    id: 'stimulant_sensitivity',
    group: 'stress',
    groupLabel: 'HOW YOUR SYSTEM RESPONDS TO LOAD',
    groupDescription: '',
    question: 'How sensitive are you to stimulants?',
    type: 'card-select',
    required: true,
    options: [
      { label: 'I can drink coffee at 5pm', value: 'low' },
      { label: 'Afternoon caffeine disrupts my sleep', value: 'moderate' },
      { label: "I'm very sensitive to stimulants", value: 'high' },
      { label: "I don't know", value: 'unknown' },
    ],
  },
  {
    id: 'wind_down_ability',
    group: 'stress',
    groupLabel: 'HOW YOUR SYSTEM RESPONDS TO LOAD',
    groupDescription: '',
    question: 'How easily can you wind down at the end of the day?',
    type: 'slider',
    sliderLabels: ['I struggle to switch off', 'I transition easily'],
    sliderMin: 1,
    sliderMax: 5,
    required: true,
  },

  // ── Group 5: Current Inputs ──
  {
    id: 'current_supplements',
    group: 'inputs',
    groupLabel: "WHAT'S ALREADY IN YOUR SYSTEM",
    groupDescription: 'Knowing your current inputs helps us avoid redundancy and interactions.',
    question: 'Are you currently taking any supplements?',
    type: 'multi-select',
    required: false,
    options: [
      { label: 'Magnesium', value: 'magnesium' },
      { label: 'Vitamin D', value: 'vitamin_d' },
      { label: 'Omega-3', value: 'omega_3' },
      { label: 'B vitamins', value: 'b_vitamins' },
      { label: 'Zinc', value: 'zinc' },
      { label: 'Ashwagandha', value: 'ashwagandha' },
      { label: 'L-theanine', value: 'l_theanine' },
      { label: 'Creatine', value: 'creatine' },
      { label: 'Melatonin', value: 'melatonin' },
      { label: 'CBD', value: 'cbd' },
      { label: 'Protein powder', value: 'protein' },
      { label: 'None', value: 'none' },
    ],
  },
  {
    id: 'current_medications',
    group: 'inputs',
    groupLabel: "WHAT'S ALREADY IN YOUR SYSTEM",
    groupDescription: '',
    question: 'Are you currently taking any medications?',
    type: 'free-text',
    required: false,
    placeholder: 'List any current medications, or leave blank',
  },
  {
    id: 'alcohol_frequency',
    group: 'inputs',
    groupLabel: "WHAT'S ALREADY IN YOUR SYSTEM",
    groupDescription: '',
    question: 'How often do you consume alcohol?',
    type: 'card-select',
    required: true,
    options: [
      { label: 'Never', value: 'never' },
      { label: 'Rarely', value: 'rarely' },
      { label: '1–2 times per week', value: '1_2' },
      { label: '3+ times per week', value: '3_plus' },
      { label: 'Daily', value: 'daily' },
    ],
  },
  {
    id: 'diet_pattern',
    group: 'inputs',
    groupLabel: "WHAT'S ALREADY IN YOUR SYSTEM",
    groupDescription: '',
    question: 'Do you follow any dietary pattern?',
    type: 'card-select',
    required: true,
    options: [
      { label: 'No restrictions', value: 'none' },
      { label: 'Vegetarian', value: 'vegetarian' },
      { label: 'Vegan', value: 'vegan' },
      { label: 'Keto / low-carb', value: 'keto' },
      { label: 'Intermittent fasting', value: 'if' },
      { label: 'Other', value: 'other' },
    ],
  },

  // ── Group 6: Safety & Constraints ──
  {
    id: 'pregnancy',
    group: 'safety',
    groupLabel: 'BOUNDARIES WE RESPECT',
    groupDescription: 'Safety constraints are non-negotiable. We ask to protect you.',
    question: 'Are you pregnant or planning pregnancy?',
    type: 'card-select',
    required: true,
    options: [
      { label: 'No', value: 'no' },
      { label: 'Yes', value: 'yes' },
      { label: 'Prefer not to say', value: 'prefer_not' },
    ],
  },
  {
    id: 'diagnosed_conditions',
    group: 'safety',
    groupLabel: 'BOUNDARIES WE RESPECT',
    groupDescription: '',
    question: 'Do you have any diagnosed conditions?',
    type: 'multi-select',
    required: false,
    options: [
      { label: 'None', value: 'none' },
      { label: 'Thyroid condition', value: 'thyroid' },
      { label: 'Autoimmune condition', value: 'autoimmune' },
      { label: 'Heart condition', value: 'heart' },
      { label: 'Seizure disorder', value: 'seizure' },
      { label: 'Psychiatric condition', value: 'psychiatric' },
      { label: 'Other', value: 'other' },
      { label: 'Prefer not to say', value: 'prefer_not' },
    ],
  },
  {
    id: 'allergies',
    group: 'safety',
    groupLabel: 'BOUNDARIES WE RESPECT',
    groupDescription: '',
    question: 'Do you have any allergies or intolerances?',
    type: 'free-text',
    required: false,
    placeholder: 'e.g., shellfish, soy, gluten — or leave blank',
  },
  {
    id: 'anything_else',
    group: 'safety',
    groupLabel: 'BOUNDARIES WE RESPECT',
    groupDescription: '',
    question: 'Anything else we should know?',
    type: 'free-text',
    required: false,
    placeholder: 'Optional — anything that might shape your protocol',
  },
];

export const questionGroups = [
  { id: 'intent', label: 'WHAT BRINGS YOU HERE', description: 'Understanding your primary objective helps us focus your protocol.' },
  { id: 'baseline', label: 'HOW YOUR DAYS TYPICALLY RUN', description: 'Your natural rhythm shapes when and how your protocol works best.' },
  { id: 'training', label: 'HOW YOUR BODY MOVES', description: 'Physical load affects recovery needs and protocol timing.' },
  { id: 'stress', label: 'HOW YOUR SYSTEM RESPONDS TO LOAD', description: 'Your nervous system patterns shape how we build your protocol.' },
  { id: 'inputs', label: "WHAT'S ALREADY IN YOUR SYSTEM", description: 'Knowing your current inputs helps us avoid redundancy and interactions.' },
  { id: 'safety', label: 'BOUNDARIES WE RESPECT', description: 'Safety constraints are non-negotiable. We ask to protect you.' },
];
