export {
  addNode,
  addEdge,
  addSourceDocument,
  addSourceChunks,
  ingestExtraction,
  contentHashFor,
} from './mutations';
export {
  getNode,
  getNodesByType,
  getSubgraphForTopic,
  getProvenanceForNode,
  getGraphRevision,
} from './queries';
export type { GraphRevision } from './queries';
export {
  NODE_TYPES,
  EDGE_TYPES,
  SOURCE_DOCUMENT_KINDS,
  decodeSourceDocumentKind,
} from './types';
export {
  FIXED_SOURCE_SYSTEMS,
  SourceRefSchema,
  encodeSourceRef,
  parseSourceRef,
  isKnownSourceSystem,
} from './source-ref';
export type { SourceSystem, SourceRef, ParsedSourceRef, FixedSourceSystem } from './source-ref';
export type {
  NodeType,
  EdgeType,
  SourceDocumentKind,
  SourceDocumentKindOrUnknown,
  AddNodeInput,
  AddEdgeInput,
  AddSourceDocumentInput,
  AddSourceChunkInput,
  SourceDocumentAliasInput,
  IngestExtractionInput,
  IngestExtractionResult,
  TopicSubgraphSpec,
  SubgraphResult,
  ProvenanceItem,
  GraphNodeRecord,
  GraphEdgeRecord,
} from './types';
export { NodeAttributesValidationError, EdgeEndpointViolation } from './errors';
export { EDGE_ENDPOINT_RULES, assertEdgeEndpoints } from './edge-validation';
export type { EdgeEndpointRule } from './edge-validation';
export {
  ATTRIBUTE_SCHEMAS,
  NodeAttributesSchema,
  parseNodeAttributes,
  validateAttributesForWrite,
  BiomarkerAttributesSchema,
  MedicationAttributesSchema,
  ConditionAttributesSchema,
  SymptomAttributesSchema,
  LifestyleAttributesSchema,
  InterventionAttributesSchema,
  MoodAttributesSchema,
  EnergyAttributesSchema,
  MetricWindowAttributesSchema,
  SourceDocumentAttributesSchema,
  AllergyAttributesSchema,
  ImmunisationAttributesSchema,
  EncounterAttributesSchema,
  ReferralAttributesSchema,
  ProcedureAttributesSchema,
  ObservationAttributesSchema,
  VITAL_SIGNS_REGISTRY,
  VITAL_SIGNS_CANONICAL_KEYS,
  resolveVitalSign,
  METRIC_WINDOW_AGGREGATIONS,
  METRIC_WINDOW_GRANULARITIES,
  OBSERVATION_CONTEXTS,
  INTERVENTION_EVENT_KINDS,
  InterventionEventAttributesSchema,
  SymptomEpisodeAttributesSchema,
  SYMPTOM_SEVERITY_SCALES,
  QUALITY_OF_LIFE_IMPACTS,
  LIFESTYLE_SUBTYPES,
  ALLERGY_REACTANT_REGISTRY,
  ALLERGY_REACTANT_CANONICAL_KEYS,
  resolveAllergyReactant,
  IMMUNISATION_VACCINE_REGISTRY,
  IMMUNISATION_CANONICAL_KEYS,
  resolveVaccine,
} from './attributes';
export type {
  AttributesByNodeType,
  AttributesFor,
  NodeAttributesEnvelope,
  UnvalidatedAttributes,
  BiomarkerAttributes,
  MedicationAttributes,
  ConditionAttributes,
  SymptomAttributes,
  LifestyleAttributes,
  InterventionAttributes,
  MoodAttributes,
  EnergyAttributes,
  MetricWindowAttributes,
  SourceDocumentAttributes,
  AllergyAttributes,
  ImmunisationAttributes,
  EncounterAttributes,
  ReferralAttributes,
  ProcedureAttributes,
  ObservationAttributes,
  AllergyReactantEntry,
  ReactantClass,
  ImmunisationVaccineEntry,
  VaccineCategory,
  VitalSignEntry,
  VitalSignContext,
  MetricWindowAggregation,
  MetricWindowGranularity,
  ObservationContext,
  InterventionEventAttributes,
  InterventionEventKind,
  SymptomEpisodeAttributes,
  SymptomSeverityScale,
  QualityOfLifeImpact,
  LifestyleSubtype,
} from './attributes';
